mj:
  discord:
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
    user-wss: true
  task-store:
    type: redis
    timeout: 30d
  translate-way: null
  queue:
    timeout-minutes: 5
    core-size: 10
    queue-size: 20
spring:
  profiles:
    active: '@profiles.active@'
logging:
  config: classpath:logging/logback-spring.xml

